FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

COPY target/*.jar app.jar

ARG DATA_BASE_URL
ARG DATA_BASE_USERNAME
ARG DATA_BASE_PASSWORD
ARG SPRING_EMAIL_HOST
ARG SPRING_EMAIL_PORT
ARG SPRING_EMAIL_USERNAME
ARG SPRING_EMAIL_PASSWORD

ENV DATA_BASE_URL=${DATA_BASE_URL} \
    DATA_BASE_USERNAME=${DATA_BASE_USERNAME} \
    DATA_BASE_PASSWORD=${DATA_BASE_PASSWORD} \
    SPRING_EMAIL_HOST=${SPRING_EMAIL_HOST} \
    SPRING_EMAIL_PORT=${SPRING_EMAIL_PORT} \
    SPRING_EMAIL_USERNAME=${SPRING_EMAIL_USERNAME} \
    SPRING_EMAIL_PASSWORD=${SPRING_EMAIL_PASSWORD}

ENTRYPOINT ["java", "-jar", "app.jar"]